/**
 * 演示物料定义 —— 仅用于演示，不属于核心库
 *
 * 覆盖三种单据类型：
 *   - KITCHEN_RECEIPT   后厨菜品小票（80mm 连续纸）
 *   - GUEST_REGISTRATION 客人入住登记单（A4 固定纸，二维网格表单）
 *   - CASHIER_RECEIPT   收银结账单（58mm 连续纸，金额合计）
 */
import type { MaterialItem } from '../designer/types'

export const DEMO_MATERIALS: MaterialItem[] = [
  // ---- KITCHEN_RECEIPT ----
  {
    type: 'value',
    name: '大字桌号',
    icon: '🪑',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'value',
      colSpan: 12,
      align: 'center',
      dataField: 'tableNo',
      style: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#000',
      },
    },
  },
  {
    type: 'label-value',
    name: '下单时间',
    icon: '🕒',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 12,
      align: 'left',
      label: '下单时间：',
      separator: '',
      dataField: 'orderTime',
      style: {
        fontSize: 12,
        color: '#333',
      },
    },
  },
  {
    type: 'label-value',
    name: '备注',
    icon: '📝',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 12,
      align: 'left',
      label: '备注：',
      separator: '',
      dataField: 'remark',
      style: {
        fontSize: 12,
        color: '#d00',
      },
    },
  },
  {
    type: 'table',
    name: '菜品清单',
    icon: '📋',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'table',
      colSpan: 12,
      align: 'left',
      bordered: false,
      rowField: 'items',
      columns: [
        { key: 'name', label: '菜品', dataField: 'name', widthMM: 50 },
        { key: 'qty', label: '数量', dataField: 'qty', widthMM: 20 },
        { key: 'unit', label: '单位', dataField: 'unit', widthMM: 18 },
      ],
      style: {
        fontSize: 13,
        color: '#000',
      },
    },
  },
  {
    type: 'image',
    name: '店铺Logo',
    icon: '🖼️',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'image',
      colSpan: 12,
      align: 'center',
      srcField: 'shop.logoUrl',
      fit: 'contain',
      style: {},
    },
  },
  {
    type: 'value',
    name: '店铺名称',
    icon: '🏪',
    documentType: 'KITCHEN_RECEIPT',
    preset: {
      type: 'value',
      colSpan: 12,
      align: 'center',
      dataField: 'shop.name',
      style: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
      },
    },
  },

  // ---- GUEST_REGISTRATION（客人入住登记单）----
  {
    type: 'value',
    name: '登记单标题',
    icon: '📋',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'value',
      colSpan: 12,
      align: 'center',
      staticText: '客人入住登记单',
      style: { fontSize: 24, fontWeight: 'bold', color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '登记单号',
    icon: '#️⃣',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'left',
      label: '登记单号：',
      separator: '',
      dataField: 'regNo',
      style: { fontSize: 12, color: '#333' },
    },
  },
  {
    type: 'label-value',
    name: '登记日期',
    icon: '📅',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'right',
      label: '登记日期：',
      separator: '',
      dataField: 'regDate',
      style: { fontSize: 12, color: '#333' },
    },
  },
  {
    type: 'label-value',
    name: '姓名',
    icon: '👤',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 8,
      align: 'left',
      label: '姓名：',
      separator: '',
      dataField: 'guest.name',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '性别',
    icon: '⚧',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 4,
      align: 'left',
      label: '性别：',
      separator: '',
      dataField: 'guest.gender',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '证件号码',
    icon: '🪪',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 8,
      align: 'left',
      label: '证件号码：',
      separator: '',
      dataField: 'guest.idNo',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '联系电话',
    icon: '📞',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'left',
      label: '联系电话：',
      separator: '',
      dataField: 'guest.phone',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '房号',
    icon: '🚪',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 4,
      align: 'left',
      label: '房号：',
      separator: '',
      dataField: 'room.no',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '房型',
    icon: '🛏️',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 4,
      align: 'left',
      label: '房型：',
      separator: '',
      dataField: 'room.type',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '入住日期',
    icon: '🔑',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'left',
      label: '入住日期：',
      separator: '',
      dataField: 'checkIn',
      style: { fontSize: 14, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '签字栏',
    icon: '✍️',
    documentType: 'GUEST_REGISTRATION',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'left',
      label: '客人签字：______________',
      separator: '',
      dataField: '',
      style: { fontSize: 14, color: '#000' },
    },
  },

  // ---- CASHIER_RECEIPT（收银结账单）----
  {
    type: 'value',
    name: '店铺名称',
    icon: '🏪',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'value',
      colSpan: 12,
      align: 'center',
      dataField: 'shop.name',
      style: { fontSize: 14, fontWeight: 'bold', color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '单号',
    icon: '#️⃣',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 12,
      align: 'left',
      label: '单号：',
      separator: '',
      dataField: 'orderNo',
      style: { fontSize: 10, color: '#333' },
    },
  },
  {
    type: 'label-value',
    name: '时间',
    icon: '🕒',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 12,
      align: 'left',
      label: '时间：',
      separator: '',
      dataField: 'payTime',
      style: { fontSize: 10, color: '#333' },
    },
  },
  {
    type: 'table',
    name: '消费明细',
    icon: '🧾',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'table',
      colSpan: 12,
      align: 'left',
      bordered: true,
      borderWidth: 1,
      borderColor: '#000',
      rowField: 'items',
      columns: [
        { key: 'name', label: '项目', dataField: 'name', widthMM: 28 },
        { key: 'amount', label: '金额', dataField: 'amount', widthMM: 22 },
      ],
      style: { fontSize: 11, color: '#000' },
    },
  },
  {
    type: 'label-value',
    name: '合计金额',
    icon: '💰',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 12,
      align: 'right',
      label: '合计：',
      separator: '',
      dataField: 'total',
      style: { fontSize: 16, fontWeight: 'bold', color: '#d00' },
    },
  },
  {
    type: 'label-value',
    name: '支付方式',
    icon: '💳',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'label-value',
      colSpan: 6,
      align: 'left',
      label: '支付：',
      separator: '',
      dataField: 'payType',
      style: { fontSize: 11, color: '#333' },
    },
  },
  {
    type: 'value',
    name: '致谢语',
    icon: '🙏',
    documentType: 'CASHIER_RECEIPT',
    preset: {
      type: 'value',
      colSpan: 12,
      align: 'center',
      staticText: '谢谢惠顾，欢迎再次光临',
      style: { fontSize: 10, color: '#999' },
    },
  },
]
