import type { DataSource, TemplateSchema } from '../designer/types'
import { PAPER_PRESETS } from '../designer/paperPresets'

/**
 * 客人登记单 —— 演示模板（A4 固定纸）
 *
 * 场景：二维网格表单、大量「标签:值」并排、固定高度
 * 重点演示：布局表格的「多列并排」能力 —— 每行 2~3 组 label-value 横向铺开
 * 纸张：A4（210×297mm 固定）
 */
export const GUEST_SCHEMA: TemplateSchema = {
  documentType: 'GUEST_REGISTRATION',
  paper: { ...PAPER_PRESETS.A4 },
  elements: [
    // 标题行
    {
      id: 'gr-title',
      name: '标题',
      type: 'value',
      row: 0,
      col: 0,
      colSpan: 12,
      align: 'center',
      staticText: '客人入住登记单',
      style: { fontSize: 24, fontWeight: 'bold', color: '#000' },
    },
    // 副标题：登记单号 + 日期（同行并排）
    {
      id: 'gr-regno',
      name: '登记单号',
      type: 'label-value',
      row: 1,
      col: 0,
      colSpan: 6,
      align: 'left',
      label: '登记单号：',
      separator: '',
      dataField: 'regNo',
      style: { fontSize: 12, color: '#333' },
    },
    {
      id: 'gr-date',
      name: '登记日期',
      type: 'label-value',
      row: 1,
      col: 6,
      colSpan: 6,
      align: 'right',
      label: '登记日期：',
      separator: '',
      dataField: 'regDate',
      style: { fontSize: 12, color: '#333' },
    },
    // 姓名 + 性别（同行并排，各占 6 列）
    {
      id: 'gr-name',
      name: '姓名',
      type: 'label-value',
      row: 2,
      col: 0,
      colSpan: 8,
      align: 'left',
      label: '姓名：',
      separator: '',
      dataField: 'guest.name',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-gender',
      name: '性别',
      type: 'label-value',
      row: 2,
      col: 8,
      colSpan: 4,
      align: 'left',
      label: '性别：',
      separator: '',
      dataField: 'guest.gender',
      style: { fontSize: 14, color: '#000' },
    },
    // 证件类型 + 证件号（同行并排）
    {
      id: 'gr-idtype',
      name: '证件类型',
      type: 'label-value',
      row: 3,
      col: 0,
      colSpan: 4,
      align: 'left',
      label: '证件类型：',
      separator: '',
      dataField: 'guest.idType',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-idno',
      name: '证件号码',
      type: 'label-value',
      row: 3,
      col: 4,
      colSpan: 8,
      align: 'left',
      label: '证件号码：',
      separator: '',
      dataField: 'guest.idNo',
      style: { fontSize: 14, color: '#000' },
    },
    // 手机 + 国籍（同行并排）
    {
      id: 'gr-phone',
      name: '联系电话',
      type: 'label-value',
      row: 4,
      col: 0,
      colSpan: 6,
      align: 'left',
      label: '联系电话：',
      separator: '',
      dataField: 'guest.phone',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-nation',
      name: '国籍',
      type: 'label-value',
      row: 4,
      col: 6,
      colSpan: 6,
      align: 'left',
      label: '国籍：',
      separator: '',
      dataField: 'guest.nationality',
      style: { fontSize: 14, color: '#000' },
    },
    // 房号 + 房型（同行并排）
    {
      id: 'gr-room',
      name: '房号',
      type: 'label-value',
      row: 5,
      col: 0,
      colSpan: 4,
      align: 'left',
      label: '房号：',
      separator: '',
      dataField: 'room.no',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-roomtype',
      name: '房型',
      type: 'label-value',
      row: 5,
      col: 4,
      colSpan: 4,
      align: 'left',
      label: '房型：',
      separator: '',
      dataField: 'room.type',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-price',
      name: '房价',
      type: 'label-value',
      row: 5,
      col: 8,
      colSpan: 4,
      align: 'left',
      label: '房价：',
      separator: '',
      dataField: 'room.price',
      style: { fontSize: 14, color: '#000' },
    },
    // 入住日期 + 离店日期（同行并排）
    {
      id: 'gr-checkin',
      name: '入住日期',
      type: 'label-value',
      row: 6,
      col: 0,
      colSpan: 6,
      align: 'left',
      label: '入住日期：',
      separator: '',
      dataField: 'checkIn',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-checkout',
      name: '离店日期',
      type: 'label-value',
      row: 6,
      col: 6,
      colSpan: 6,
      align: 'left',
      label: '离店日期：',
      separator: '',
      dataField: 'checkOut',
      style: { fontSize: 14, color: '#000' },
    },
    // 签字栏（同行并排：客人签字 + 经办人）
    {
      id: 'gr-sign-guest',
      name: '客人签字',
      type: 'label-value',
      row: 7,
      col: 0,
      colSpan: 6,
      align: 'left',
      label: '客人签字：______________',
      separator: '',
      dataField: '',
      style: { fontSize: 14, color: '#000' },
    },
    {
      id: 'gr-sign-staff',
      name: '经办人',
      type: 'label-value',
      row: 7,
      col: 6,
      colSpan: 6,
      align: 'right',
      label: '经办人：______________',
      separator: '',
      dataField: '',
      style: { fontSize: 14, color: '#000' },
    },
  ],
}

/** 客人登记单数据源 */
export const GUEST_DATA: DataSource = {
  regNo: 'REG-20260614-0088',
  regDate: '2026-06-14',
  guest: {
    name: '张伟',
    gender: '男',
    idType: '身份证',
    idNo: '310101199003071234',
    phone: '138****5678',
    nationality: '中国',
  },
  room: {
    no: '808',
    type: '豪华大床房',
    price: '¥588/晚',
  },
  checkIn: '2026-06-14 14:20',
  checkOut: '2026-06-16 12:00',
}

/**
 * 收银结账单 —— 演示模板（58mm 连续纸）
 *
 * 场景：超窄幅小票、紧凑排版、金额合计
 * 重点演示：58mm 极窄纸下的多列并排（店名满宽、明细表、合计行加粗）+ 金额对齐
 * 纸张：58mm 连续纸
 */
export const CASHIER_SCHEMA: TemplateSchema = {
  documentType: 'CASHIER_RECEIPT',
  paper: { ...PAPER_PRESETS.PAPER_58MM },
  elements: [
    // 店名
    {
      id: 'cs-shop',
      name: '店铺名称',
      type: 'value',
      row: 0,
      col: 0,
      colSpan: 12,
      align: 'center',
      dataField: 'shop.name',
      style: { fontSize: 14, fontWeight: 'bold', color: '#000' },
    },
    // 单号 + 时间（同行并排）
    {
      id: 'cs-no',
      name: '单号',
      type: 'label-value',
      row: 1,
      col: 0,
      colSpan: 12,
      align: 'left',
      label: '单号：',
      separator: '',
      dataField: 'orderNo',
      style: { fontSize: 10, color: '#333' },
    },
    {
      id: 'cs-time',
      name: '时间',
      type: 'label-value',
      row: 2,
      col: 0,
      colSpan: 12,
      align: 'left',
      label: '时间：',
      separator: '',
      dataField: 'payTime',
      style: { fontSize: 10, color: '#333' },
    },
    // 明细表（带表格线）
    {
      id: 'cs-items',
      name: '消费明细',
      type: 'table',
      row: 3,
      col: 0,
      colSpan: 12,
      align: 'left',
      bordered: true,
      borderWidth: 1,
      borderColor: '#000',
      rowField: 'items',
      columns: [
        { key: 'name', label: '项目', dataField: 'name', widthMM: 28 },
        { key: 'amount', label: '金额', dataField: 'amount', widthMM: 22 },
      ],
      style: { fontSize: 11, color: '#000' },
    },
    // 合计（满宽，加粗放大）
    {
      id: 'cs-total',
      name: '合计金额',
      type: 'label-value',
      row: 4,
      col: 0,
      colSpan: 12,
      align: 'right',
      label: '合计：',
      separator: '',
      dataField: 'total',
      style: { fontSize: 16, fontWeight: 'bold', color: '#d00' },
    },
    // 支付方式 + 实付（同行并排）
    {
      id: 'cs-paytype',
      name: '支付方式',
      type: 'label-value',
      row: 5,
      col: 0,
      colSpan: 6,
      align: 'left',
      label: '支付：',
      separator: '',
      dataField: 'payType',
      style: { fontSize: 11, color: '#333' },
    },
    {
      id: 'cs-paid',
      name: '实付',
      type: 'label-value',
      row: 5,
      col: 6,
      colSpan: 6,
      align: 'right',
      label: '实付：',
      separator: '',
      dataField: 'paid',
      style: { fontSize: 11, color: '#333' },
    },
    // 致谢
    {
      id: 'cs-thanks',
      name: '致谢',
      type: 'value',
      row: 6,
      col: 0,
      colSpan: 12,
      align: 'center',
      staticText: '谢谢惠顾，欢迎再次光临',
      style: { fontSize: 10, color: '#999' },
    },
  ],
}

/** 收银结账单数据源 */
export const CASHIER_DATA: DataSource = {
  shop: { name: '便利蜂·人民路店' },
  orderNo: '20260614088',
  payTime: '2026-06-14 12:35:08',
  items: [
    { name: '矿泉水 550ml', amount: '¥2.00' },
    { name: '三明治-火腿蛋', amount: '¥8.50' },
    { name: '美式咖啡 中', amount: '¥12.00' },
    { name: '纸巾', amount: '¥1.00' },
    // 合计行：行级样式覆写
    { name: '小计', amount: '¥23.50', _rowStyle: { fontWeight: 'bold' } },
  ],
  total: '¥23.50',
  payType: '微信支付',
  paid: '¥23.50',
}
